"""empty message

Revision ID: 14c796ddb6b4
Revises: 
Create Date: 2020-05-28 13:50:49.425343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c796ddb6b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('vote_up', sa.Integer(), nullable=False),
    sa.Column('vote_down', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_path'), 'comment', ['path'], unique=False)
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=2000), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('vote_up', sa.Integer(), nullable=False),
    sa.Column('vote_down', sa.Integer(), nullable=False),
    sa.Column('vote_flat', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=600), nullable=False),
    sa.Column('official', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=900), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('filter', sa.String(length=20), nullable=False),
    sa.Column('image_link', sa.String(length=900), nullable=False),
    sa.Column('news_link', sa.String(length=900), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('other', sa.String(length=4), nullable=False),
    sa.Column('county', sa.String(length=4), nullable=False),
    sa.Column('age', sa.String(length=3), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('symptoms', sa.String(length=120), nullable=False),
    sa.Column('underlying', sa.String(length=120), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_timestamp'), 'vote', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_timestamp'), table_name='vote')
    op.drop_table('vote')
    op.drop_table('user')
    op.drop_table('update')
    op.drop_table('person')
    op.drop_table('news')
    op.drop_table('local')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_index(op.f('ix_comment_path'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
