"""empty message

Revision ID: 8f441be81e52
Revises: ba172b854b1a
Create Date: 2020-05-28 13:26:51.083494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f441be81e52'
down_revision = 'ba172b854b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ke', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ke')
    # ### end Alembic commands ###
